# Generated by Django 4.2.8 on 2023-12-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dartaapp', '0002_bookdetail_alter_customer_book_delete_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction',
            new_name='transaction_date',
        ),
    ]
