# Generated by Django 4.2.8 on 2023-12-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartaapp', '0003_rename_transaction_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
